const OK = 200;
const CREATED = 201;
const BAD_REQUEST = 400; // BAD_REQUEST
const UNAUTHORIZED = 401; // UNAUTHORIZED
const ERROR_ACCESS = 403;
const NOT_FOUND = 404;
const NOT_UNIQUE = 409; //CONFLICT
const INTERNAL_SERVER_ERROR = 500; // INTERNAL_SERVER_ERROR

module.exports = {
  OK,
  CREATED,
  BAD_REQUEST,
  UNAUTHORIZED,
  ERROR_ACCESS,
  NOT_FOUND,
  NOT_UNIQUE,
  INTERNAL_SERVER_ERROR
};
